### ISSUE TITLE
App can't connect since version 2.4.0

### ISSUE THREAD

**Issue by RicardoVelaC** [Cantallops/Phantom#3]
1. After update to Ghost 2.4.0 app only show a white screen.

2. In a fresh install, app can't connect and show error message "It has been impossible detect a Ghost installation"

**Comment by Cantallops** [comment]
@RicardoVelaC thank you for the report. I just move to another country so for the moment I am not able to maintain the app. I hope I will found some spare time to keep the app update.  

Sorry :/

**Comment by RicardoVelaC** [comment]
Ok, only was problem with my DNS.
Sorry for that.
